# Site settings
name: Aviral Jain
title: Aviral Jain | Portfolio
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://github.com/jainaviral898/jainaviral898.github.io/
baseurl: https://github.com/jainaviral898/jainaviral898.github.io/
email: jainaviral898@gmail.com
cover: https://github.com/jainaviral898/jainaviral898.github.io/img/og.png
logo: https://github.com/jainaviral898/jainaviral898.github.io/img/emojis/technologist.png
resume: https://github.com/jainaviral898/jainaviral898.github.io/resume.pdf
social:
  - title: email
    url: mailto:jainaviral898@gmail.com
  - title: twitter
    url: https://twitter.com/juniorninja_18
  - title: instagram
    url: https://instagram.com/_aviraljain
  - title: github
    url: https://github.com/jainaviral898
  - title: linkedin
    url: https://www.linkedin.com/in/jainaviral898/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
