# Site settings
name: Aviral Jain
title: Aviral Jain | Portfolio
description: Final year undergrad student @ IIT Kharagpur, with a passion for solving problems with creative thinking. Always looking for new opportunities to learn and grow.
url: https://jainaviral898.github.io/jekyll-portfolio/
baseurl: https://jainaviral898.github.io/jekyll-portfolio/
email: jainaviral898@gmail.com
cover: https://jainaviral898.github.io/jekyll-portfolio/img/og.png
logo: https://jainaviral898.github.io/jekyll-portfolio/img/emojis/technologist.png
resume: https://jainaviral898.github.io/jekyll-portfolio/resume.pdf
social:
  - title: email
    url: mailto:jainaviral898@gmail.com
  - title: twitter
    url: https://twitter.com/juniorninja_18
  - title: instagram
    url: https://instagram.com/_aviraljain
  - title: github
    url: https://github.com/jainaviral898
  - title: linkedin
    url: https://www.linkedin.com/in/jainaviral898/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
